import type { DbGame, Vertical, VibeType } from "./types";

// Seeded into the games table via supabase/seeds/games.sql
// is_native = true means the game runs inside Field Day
// is_native = false means we link out to an external URL

export const GAMES_SEED: Omit<DbGame, "id">[] = [
  // ─── Native games ───────────────────────────────────────────────────────────
  {
    slug: "wavelength",
    name: "Wavelength",
    description:
      "Place a marker on a spectrum for the same prompt. See how your minds align — or don't.",
    type: "collaborative",
    duration_min: 10,
    duration_max: 20,
    is_native: true,
    external_url: null,
    compatible_verticals: ["dating", "school", "friends", "work"] as Vertical[],
    vibe_tags: ["explorer", "creator", "wanderer"] as VibeType[],
  },
  {
    slug: "hot-take",
    name: "Hot Take",
    description:
      "Rate a statement 1–10. Both players answer the same 5 prompts independently, then compare.",
    type: "collaborative",
    duration_min: 5,
    duration_max: 10,
    is_native: true,
    external_url: null,
    compatible_verticals: ["dating", "school", "friends", "work"] as Vertical[],
    vibe_tags: ["challenger", "creator"] as VibeType[],
  },
  {
    slug: "this-or-that",
    name: "This or That",
    description:
      "15 rapid-fire binary choices. See how many you matched on.",
    type: "collaborative",
    duration_min: 5,
    duration_max: 8,
    is_native: true,
    external_url: null,
    compatible_verticals: ["dating", "school", "friends", "work"] as Vertical[],
    vibe_tags: ["wanderer", "explorer"] as VibeType[],
  },
  {
    slug: "story-chain",
    name: "Story Chain",
    description:
      "You write the first sentence. They write the next. 8 turns. See what story you build together.",
    type: "storytelling",
    duration_min: 10,
    duration_max: 30,
    is_native: true,
    external_url: null,
    compatible_verticals: ["dating", "school", "friends"] as Vertical[],
    vibe_tags: ["creator", "wanderer"] as VibeType[],
  },

  // ─── External games ─────────────────────────────────────────────────────────
  {
    slug: "wordle",
    name: "Wordle",
    description: "The classic five-letter word puzzle. Compare your scores.",
    type: "daily-puzzle",
    duration_min: 3,
    duration_max: 8,
    is_native: false,
    external_url: "https://www.nytimes.com/games/wordle/index.html",
    compatible_verticals: ["dating", "school", "friends", "work"] as Vertical[],
    vibe_tags: ["explorer", "wanderer"] as VibeType[],
  },
  {
    slug: "connections",
    name: "Connections",
    description: "Group 16 words into 4 categories. See if you see the same patterns.",
    type: "daily-puzzle",
    duration_min: 5,
    duration_max: 15,
    is_native: false,
    external_url: "https://www.nytimes.com/games/connections",
    compatible_verticals: ["dating", "school", "friends", "work"] as Vertical[],
    vibe_tags: ["creator", "wanderer"] as VibeType[],
  },
  {
    slug: "worldle",
    name: "Worldle",
    description: "Guess the country by its silhouette. Geography nerds unite.",
    type: "daily-puzzle",
    duration_min: 3,
    duration_max: 8,
    is_native: false,
    external_url: "https://worldle.teuteuf.fr/",
    compatible_verticals: ["dating", "school", "friends"] as Vertical[],
    vibe_tags: ["explorer", "wanderer"] as VibeType[],
  },
  {
    slug: "framed",
    name: "Framed",
    description: "Guess the movie from a single frame. Cinephile edition.",
    type: "daily-puzzle",
    duration_min: 3,
    duration_max: 8,
    is_native: false,
    external_url: "https://framed.wtf/",
    compatible_verticals: ["dating", "friends"] as Vertical[],
    vibe_tags: ["creator", "wanderer"] as VibeType[],
  },
  {
    slug: "heardle",
    name: "Heardle",
    description: "Guess the song from a short clip. Music taste reveal.",
    type: "daily-puzzle",
    duration_min: 3,
    duration_max: 8,
    is_native: false,
    external_url: "https://www.spotify.com/heardle/",
    compatible_verticals: ["dating", "friends", "school"] as Vertical[],
    vibe_tags: ["creator", "explorer"] as VibeType[],
  },
  {
    slug: "typeracer",
    name: "TypeRacer",
    description: "Race to type a quote the fastest. Competitive typing, raw speed.",
    type: "competitive",
    duration_min: 5,
    duration_max: 10,
    is_native: false,
    external_url: "https://play.typeracer.com/",
    compatible_verticals: ["dating", "school", "friends", "work"] as Vertical[],
    vibe_tags: ["challenger", "explorer"] as VibeType[],
  },
  {
    slug: "lichess",
    name: "Chess (Lichess)",
    description: "Play a game of chess. The ultimate patience test.",
    type: "competitive",
    duration_min: 10,
    duration_max: 60,
    is_native: false,
    external_url: "https://lichess.org/",
    compatible_verticals: ["dating", "friends", "work"] as Vertical[],
    vibe_tags: ["challenger", "explorer"] as VibeType[],
  },
  {
    slug: "keymash",
    name: "Keymash",
    description: "Mash the keyboard in patterns. Pure chaotic speed.",
    type: "competitive",
    duration_min: 3,
    duration_max: 5,
    is_native: false,
    external_url: "https://keymash.io/",
    compatible_verticals: ["school", "friends"] as Vertical[],
    vibe_tags: ["challenger", "wanderer"] as VibeType[],
  },
  {
    slug: "gartic-phone",
    name: "Gartic Phone",
    description: "Draw a prompt, pass it along, watch the game of telephone unfold.",
    type: "creative",
    duration_min: 20,
    duration_max: 40,
    is_native: false,
    external_url: "https://garticphone.com/",
    compatible_verticals: ["dating", "school", "friends"] as Vertical[],
    vibe_tags: ["creator", "wanderer"] as VibeType[],
  },
  {
    slug: "skribbl",
    name: "Skribbl.io",
    description: "One player draws, the rest guess. Classic party energy.",
    type: "creative",
    duration_min: 15,
    duration_max: 30,
    is_native: false,
    external_url: "https://skribbl.io/",
    compatible_verticals: ["school", "friends"] as Vertical[],
    vibe_tags: ["creator", "wanderer"] as VibeType[],
  },
  {
    slug: "codenames",
    name: "Codenames",
    description:
      "One-word clues, multiple words to cover. The ultimate test of how you think.",
    type: "collaborative",
    duration_min: 20,
    duration_max: 40,
    is_native: false,
    external_url: "https://codenames.game/",
    compatible_verticals: ["dating", "friends", "work"] as Vertical[],
    vibe_tags: ["challenger", "creator"] as VibeType[],
  },
  {
    slug: "semantle",
    name: "Semantle",
    description: "Guess a secret word by semantic similarity. Deeply nerdy.",
    type: "daily-puzzle",
    duration_min: 10,
    duration_max: 30,
    is_native: false,
    external_url: "https://semantle.com/",
    compatible_verticals: ["dating", "school", "friends"] as Vertical[],
    vibe_tags: ["explorer", "creator"] as VibeType[],
  },
  {
    slug: "openguessr",
    name: "OpenGuessr",
    description: "Drop a pin on a Google Street View location. Geography geek dream.",
    type: "competitive",
    duration_min: 10,
    duration_max: 20,
    is_native: false,
    external_url: "https://openguessr.com/",
    compatible_verticals: ["dating", "school", "friends"] as Vertical[],
    vibe_tags: ["explorer", "challenger"] as VibeType[],
  },
  {
    slug: "battleship",
    name: "Battleship",
    description: "Classic grid-based warfare. Sink their fleet.",
    type: "competitive",
    duration_min: 15,
    duration_max: 30,
    is_native: false,
    external_url: "https://www.battleship-game.org/",
    compatible_verticals: ["school", "friends", "work"] as Vertical[],
    vibe_tags: ["challenger", "wanderer"] as VibeType[],
  },
];

// Game slugs that require async-only (can't be played live easily)
export const ASYNC_ONLY_GAMES = new Set([
  "wordle",
  "connections",
  "worldle",
  "framed",
  "heardle",
  "semantle",
]);

// Games unsuitable for short sessions (>15 min)
export const LONG_GAMES = new Set([
  "lichess",
  "gartic-phone",
  "codenames",
  "story-chain",
  "battleship",
]);
